# Generated by Django 4.2.6 on 2023-11-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(default='9999', max_length=9),
            preserve_default=False,
        ),
    ]
