# Generated by Django 4.2.6 on 2023-11-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='password@gbistrong', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
