# Generated by Django 4.2.6 on 2024-01-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deviceToken',
            field=models.TextField(blank=True, null=True),
        ),
    ]
