# Generated by Django 4.2.6 on 2023-12-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfragment',
            name='position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
