# Generated by Django 4.2.6 on 2023-12-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_postfragment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=225),
        ),
    ]
