# Generated by Django 4.2.6 on 2023-11-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='acadamic_year',
            field=models.CharField(choices=[('NR', 'Not Registered'), ('FM', 'FreshMan'), ('SY', 'Second Year'), ('TY', 'Thered Year'), ('FY', 'Fourth Year'), ('GC', 'Fivth Year')], default='NR', max_length=2),
        ),
    ]
