# Generated by Django 4.2.6 on 2023-11-08 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0002_alter_profile_acadamic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='authority',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='group',
            field=models.ManyToManyField(to='Profile.group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='admins',
            field=models.ManyToManyField(related_name='admins', to=settings.AUTH_USER_MODEL),
        ),
    ]
