# Generated by Django 4.2.6 on 2023-11-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_profile_authority_profile_group_alter_group_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='sub_groups',
            field=models.ManyToManyField(blank=True, to='Profile.group'),
        ),
    ]
