# Generated by Django 4.2.6 on 2023-12-31 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anouncementpost',
            name='image',
        ),
    ]
