# Generated by Django 4.2.6 on 2024-01-10 10:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_phonenumber'),
        ('Messages', '0002_remove_anouncementpost_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassSms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('errorPhoneNumbers', models.TextField()),
                ('errorCount', models.IntegerField()),
                ('sucessCount', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.group')),
            ],
        ),
    ]
