# Generated by Django 4.2.6 on 2024-01-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0003_masssms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masssms',
            name='errorPhoneNumbers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
